print("Welcome to the Band Name Generator")
print("Let's get started!")
city = input("What's the name of the city you grew up in?\n:")
pet = input("What's the name of your first pet?\n:")
print("Your band name could be " + city + " " + pet + "!")